# Generated by Django 5.2.8 on 2025-11-30 22:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompSciDeptID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('location1', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('face', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='CompSciLabs',
            fields=[
                ('abbr', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CompSciLabID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issued_at', models.DateField(db_default=datetime.datetime(2025, 12, 1, 6, 31, 23, 51975))),
                ('file', models.FileField(upload_to='uploads/')),
                ('verified', models.BooleanField(default=False)),
                ('csdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.compscideptid')),
                ('cslab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.compscilabs')),
            ],
        ),
    ]
