# Generated by Django 5.2.8 on 2025-11-30 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(db_default=datetime.datetime(2025, 12, 1, 6, 31, 37, 335804)),
        ),
    ]
