# Generated by Django 5.2.8 on 2025-12-01 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_compscilabid_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(db_default=datetime.datetime(2025, 12, 1, 8, 55, 5, 246824)),
        ),
    ]
