# Generated by Django 5.2.8 on 2025-12-01 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_compscilabid_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(db_default=datetime.datetime(2025, 12, 1, 12, 11, 22, 114612)),
        ),
        migrations.AlterField(
            model_name='compscilabs',
            name='abbr',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
