# Generated by Django 5.2.8 on 2025-12-01 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_compscilabid_issued_at_alter_compscilabs_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='csdept',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(db_default=datetime.datetime(2025, 12, 1, 12, 49, 9, 894899)),
        ),
    ]
