# Generated by Django 5.2.8 on 2025-12-01 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_alter_compscilabid_csdept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='cslab',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(db_default=datetime.datetime(2025, 12, 1, 13, 7, 36, 727303)),
        ),
    ]
