# Generated by Django 5.2.8 on 2025-12-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_alter_compscilabid_cslab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscilabid',
            name='csdept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.compscideptid'),
        ),
        migrations.AlterField(
            model_name='compscilabid',
            name='cslab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.compscilabs'),
        ),
        migrations.AlterField(
            model_name='compscilabid',
            name='issued_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
