# Generated by Django 5.2.8 on 2025-12-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_alter_compscilabid_csdept_alter_compscilabid_cslab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscideptid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='compscideptid',
            name='face',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compscideptid',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
