# Generated by Django 5.2.8 on 2025-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_alter_compscideptid_email_alter_compscideptid_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compscideptid',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
