# Generated by Django 5.2.8 on 2026-01-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_alter_compscideptid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pcn', models.IntegerField(unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='compscilabid',
            name='csdept',
        ),
        migrations.RemoveField(
            model_name='compscilabid',
            name='cslab',
        ),
        migrations.DeleteModel(
            name='CompSciDeptID',
        ),
        migrations.DeleteModel(
            name='CompSciLabID',
        ),
        migrations.DeleteModel(
            name='CompSciLabs',
        ),
    ]
