# Generated by Django 5.2.8 on 2026-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_user_remove_compscilabid_csdept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, null=True),
        ),
    ]
