# Generated by Django 5.2.8 on 2026-01-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_user_birthdate_user_name_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, null=True),
        ),
    ]
