# Generated by Django 5.2.3 on 2026-04-22 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_claims_per_user', models.PositiveIntegerField(default=1)),
                ('claim_type', models.CharField(blank=True, choices=[('once', 'Once'), ('periodic', 'Periodic')], max_length=20, null=True)),
                ('claim_interval', models.CharField(blank=True, choices=[('periodic', 'Periodic'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], max_length=20, null=True)),
                ('stocks', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('recepient_sectors', models.ManyToManyField(to='residents.residentsector')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClaim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, editable=False, unique=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_claims', to='residents.resident')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayService',
            fields=[
            ],
            options={
                'verbose_name': 'Giveaway Claims',
                'verbose_name_plural': 'Giveaway Claims',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.serviceclaim',),
        ),
        migrations.AddIndex(
            model_name='serviceclaim',
            index=models.Index(fields=['user', 'service', 'claimed_at'], name='service_ser_user_id_e34db5_idx'),
        ),
    ]
