# Generated by Django 5.2.8 on 2026-04-11 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stocks', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClaim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, editable=False, unique=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_claims', to='residents.user')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationBenefitsService',
            fields=[
            ],
            options={
                'verbose_name': 'Registration Benefits Claims',
                'verbose_name_plural': 'Registration Benefits Claims',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.serviceclaim',),
        ),
        migrations.CreateModel(
            name='WeeklyStipendService',
            fields=[
            ],
            options={
                'verbose_name': 'Weekly Stipend Claims',
                'verbose_name_plural': 'Weekly Stipend Claims',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.serviceclaim',),
        ),
        migrations.AddIndex(
            model_name='serviceclaim',
            index=models.Index(fields=['user', 'service', 'claimed_at'], name='service_ser_user_id_e34db5_idx'),
        ),
    ]
