# Generated by Django 5.2.8 on 2026-04-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationBenefitsService',
        ),
        migrations.DeleteModel(
            name='WeeklyStipendService',
        ),
        migrations.CreateModel(
            name='GiveawayService',
            fields=[
            ],
            options={
                'verbose_name': 'Giveaway Claims',
                'verbose_name_plural': 'Giveaway Claims',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.serviceclaim',),
        ),
        migrations.AddField(
            model_name='serviceclaim',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
