# Generated by Django 5.2.8 on 2026-03-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_user_phone_number'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceclaim',
            options={'ordering': ['-claimed_at']},
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceclaim',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='service.service'),
        ),
        migrations.AlterField(
            model_name='serviceclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_claims', to='residents.user'),
        ),
    ]
