# Generated by Django 5.2.3 on 2026-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclaim',
            name='notes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
