# Generated by Django 5.2.8 on 2026-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stocks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
