# Generated by Django 5.2.8 on 2026-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclaim',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
