# Generated by Django 5.2.8 on 2026-05-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_refresh_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='recepient_sectors',
            new_name='recipient_sectors',
        ),
    ]
