# Generated by Django 5.2.8 on 2026-04-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_registrationbenefitsservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='claim_interval',
            field=models.CharField(blank=True, choices=[('periodic', 'Periodic'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('periodic', 'Periodic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_claims_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
