# Generated by Django 5.2.3 on 2026-04-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceclaim_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiveawayService',
        ),
    ]
