# Generated by Django 5.2.8 on 2026-05-14 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_alter_resident_profile_image_and_more'),
        ('service', '0003_serviceclaim_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceClaim',
            new_name='Claim',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='service_cla_user_id_bc3275_idx',
            old_name='service_ser_user_id_e34db5_idx',
        ),
    ]
