# Generated by Django 5.2.8 on 2026-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameError', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pcn', models.IntegerField(unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('proof_of_residence', models.FileField(upload_to='uploads/')),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('face_data', models.BinaryField(default=b'')),
            ],
        ),
    ]
