# Generated by Django 5.2.8 on 2026-04-09 07:15

import residents.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameError', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pcn', models.IntegerField(db_index=True, unique=True, verbose_name='PCN')),
                ('uin', models.CharField(db_index=True, default=residents.generator.generate_uid, editable=False, unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('proof_of_residence', models.FileField(upload_to='proofs/')),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
