# Generated by Django 5.2.8 on 2026-05-16 08:53

import residents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pcn', models.CharField(db_index=True, unique=True, verbose_name='PCN')),
                ('uin', models.CharField(db_index=True, editable=False, unique=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('proof_of_residence', models.FileField(upload_to=residents.models.proof_upload_to)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(upload_to=residents.models.image_upload_to)),
                ('sector', models.ManyToManyField(related_name='sectors', to='residents.sector')),
            ],
        ),
    ]
