# Generated by Django 5.2.8 on 2026-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentsector',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='residentsector',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
