# Generated by Django 5.2.8 on 2026-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameError', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='file',
            new_name='proof_of_residence',
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(to='residents.service'),
        ),
    ]
