# Generated by Django 5.2.8 on 2026-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pcn',
            field=models.CharField(db_index=True, unique=True, verbose_name='PCN'),
        ),
    ]
