# Generated by Django 5.2.8 on 2026-05-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentSector',
            new_name='Sector',
        ),
    ]
