# Generated by Django 5.2.8 on 2026-05-26 04:12

import residents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=residents.models.image_upload_to),
        ),
    ]
