# Generated by Django 5.2.8 on 2026-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_services',
            field=models.ManyToManyField(blank=True, to='service.service'),
        ),
    ]
