# Generated by Django 5.2.8 on 2026-05-02 13:48

import residents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_remove_residentsector_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='profile_image',
            field=models.ImageField(upload_to=residents.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='resident',
            name='proof_of_residence',
            field=models.FileField(upload_to=residents.models.proof_upload_to),
        ),
    ]
