# Generated by Django 6.0.1 on 2026-02-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_service_rename_file_user_proof_of_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='services',
        ),
    ]
