# Generated by Django 5.2.8 on 2026-03-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_remove_user_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
