# Generated by Django 5.2.8 on 2026-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_user_email_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
